USE best_foot;

INSERT INTO users (name, age) VALUES ('Amogh', 24);
INSERT INTO users (name, age) VALUES ('Bob', 44);

INSERT INTO blurbs (user_id, blurb) VALUES (1, 'I used to say I liked hiking, but then I moved here and I discovered what "mountains" are. Fun fact: they''re much bigger than hills');
INSERT INTO blurbs (user_id, blurb) VALUES (1, 'I like ambitious people who want to do any of the following: cooking, biking, karaoke, walking around the city');
INSERT INTO blurbs (user_id, blurb) VALUES (2, 'My passions in life are making burgers . . . and I guess that''s about it');
INSERT INTO blurbs (user_id, blurb) VALUES (2, 'Fun fact about me: I used to be a night time cab driver in Ocean City, NJ. You meet a LOT of interesting people!');


INSERT INTO pictures (user_id, picture_url) VALUES (1, './pics/amogh/1.jpg');
INSERT INTO pictures (user_id, picture_url) VALUES (1, './pics/amogh/2.jpg');
INSERT INTO pictures (user_id, picture_url) VALUES (1, './pics/amogh/3.png');
INSERT INTO pictures (user_id, picture_url) VALUES (1, './pics/amogh/4.png');
INSERT INTO pictures (user_id, picture_url) VALUES (1, './pics/amogh/5.png');
INSERT INTO pictures (user_id, picture_url) VALUES (1, './pics/amogh/6.png');
INSERT INTO pictures (user_id, picture_url) VALUES (2, './pics/bob/1.jpg');
INSERT INTO pictures (user_id, picture_url) VALUES (2, './pics/bob/2.jpg');
INSERT INTO pictures (user_id, picture_url) VALUES (2, './pics/bob/3.jpg');
INSERT INTO pictures (user_id, picture_url) VALUES (2, './pics/bob/4.png');
INSERT INTO pictures (user_id, picture_url) VALUES (2, './pics/bob/5.png');


INSERT INTO ratings (picture_id, rating) VALUES(1, 0);
INSERT INTO ratings (picture_id, rating) VALUES(1, 1);
INSERT INTO ratings (picture_id, rating) VALUES(1, 0);
INSERT INTO ratings (picture_id, rating) VALUES(1, 1);
INSERT INTO ratings (picture_id, rating) VALUES(2, 0);
INSERT INTO ratings (picture_id, rating) VALUES(2, 1);
INSERT INTO ratings (picture_id, rating) VALUES(2, 1);
INSERT INTO ratings (picture_id, rating) VALUES(2, 1);
INSERT INTO ratings (picture_id, rating) VALUES(3, 0);
INSERT INTO ratings (picture_id, rating) VALUES(3, 1);
INSERT INTO ratings (picture_id, rating) VALUES(3, 0);
INSERT INTO ratings (picture_id, rating) VALUES(3, 1);
INSERT INTO ratings (picture_id, rating) VALUES(4, 0);
INSERT INTO ratings (picture_id, rating) VALUES(5, 1);
INSERT INTO ratings (picture_id, rating) VALUES(4, 1);
INSERT INTO ratings (picture_id, rating) VALUES(4, 1);
INSERT INTO ratings (picture_id, rating) VALUES(5, 0);
INSERT INTO ratings (picture_id, rating) VALUES(6, 1);
INSERT INTO ratings (picture_id, rating) VALUES(7, 0);
INSERT INTO ratings (picture_id, rating) VALUES(6, 1);
INSERT INTO ratings (picture_id, rating) VALUES(5, 0);
INSERT INTO ratings (picture_id, rating) VALUES(6, 1);
INSERT INTO ratings (picture_id, rating) VALUES(7, 1);
INSERT INTO ratings (picture_id, rating) VALUES(5, 1);
INSERT INTO ratings (picture_id, rating) VALUES(4, 0);
INSERT INTO ratings (picture_id, rating) VALUES(5, 1);
INSERT INTO ratings (picture_id, rating) VALUES(4, 0);
INSERT INTO ratings (picture_id, rating) VALUES(7, 1);
INSERT INTO ratings (picture_id, rating) VALUES(7, 0);
INSERT INTO ratings (picture_id, rating) VALUES(5, 1);
INSERT INTO ratings (picture_id, rating) VALUES(2, 1);
INSERT INTO ratings (picture_id, rating) VALUES(2, 1);
INSERT INTO ratings (picture_id, rating) VALUES(1, 0);
INSERT INTO ratings (picture_id, rating) VALUES(1, 1);
INSERT INTO ratings (picture_id, rating) VALUES(1, 0);
INSERT INTO ratings (picture_id, rating) VALUES(4, 1);
INSERT INTO ratings (picture_id, rating) VALUES(4, 0);
INSERT INTO ratings (picture_id, rating) VALUES(4, 1);
INSERT INTO ratings (picture_id, rating) VALUES(4, 1);
INSERT INTO ratings (picture_id, rating) VALUES(4, 1);
INSERT INTO ratings (picture_id, rating) VALUES(4, 0);
INSERT INTO ratings (picture_id, rating) VALUES(4, 1);
INSERT INTO ratings (picture_id, rating) VALUES(4, 0);
INSERT INTO ratings (picture_id, rating) VALUES(4, 1);
INSERT INTO ratings (picture_id, rating) VALUES(7, 0);
INSERT INTO ratings (picture_id, rating) VALUES(7, 1);
INSERT INTO ratings (picture_id, rating) VALUES(7, 1);
INSERT INTO ratings (picture_id, rating) VALUES(7, 1);
INSERT INTO ratings (picture_id, rating) VALUES(7, 0);
INSERT INTO ratings (picture_id, rating) VALUES(1, 1);
INSERT INTO ratings (picture_id, rating) VALUES(6, 0);
INSERT INTO ratings (picture_id, rating) VALUES(6, 1);
INSERT INTO ratings (picture_id, rating) VALUES(6, 0);
INSERT INTO ratings (picture_id, rating) VALUES(6, 1);
INSERT INTO ratings (picture_id, rating) VALUES(6, 1);
INSERT INTO ratings (picture_id, rating) VALUES(5, 1);
INSERT INTO ratings (picture_id, rating) VALUES(5, 0);
INSERT INTO ratings (picture_id, rating) VALUES(5, 1);
INSERT INTO ratings (picture_id, rating) VALUES(5, 0);
INSERT INTO ratings (picture_id, rating) VALUES(5, 1);
INSERT INTO ratings (picture_id, rating) VALUES(5, 0);
INSERT INTO ratings (picture_id, rating) VALUES(8, 1);
INSERT INTO ratings (picture_id, rating) VALUES(8, 1);
INSERT INTO ratings (picture_id, rating) VALUES(8, 1);
INSERT INTO ratings (picture_id, rating) VALUES(8, 0);
INSERT INTO ratings (picture_id, rating) VALUES(8, 1);
INSERT INTO ratings (picture_id, rating) VALUES(8, 0);
INSERT INTO ratings (picture_id, rating) VALUES(8, 1);
INSERT INTO ratings (picture_id, rating) VALUES(8, 1);
INSERT INTO ratings (picture_id, rating) VALUES(9, 1);
INSERT INTO ratings (picture_id, rating) VALUES(9, 0);
INSERT INTO ratings (picture_id, rating) VALUES(9, 1);
INSERT INTO ratings (picture_id, rating) VALUES(9, 0);
INSERT INTO ratings (picture_id, rating) VALUES(10, 1);
INSERT INTO ratings (picture_id, rating) VALUES(10, 1);
INSERT INTO ratings (picture_id, rating) VALUES(10, 1);
INSERT INTO ratings (picture_id, rating) VALUES(10, 0);
INSERT INTO ratings (picture_id, rating) VALUES(10, 1);
INSERT INTO ratings (picture_id, rating) VALUES(10, 1);
INSERT INTO ratings (picture_id, rating) VALUES(10, 1);
INSERT INTO ratings (picture_id, rating) VALUES(11, 0);
INSERT INTO ratings (picture_id, rating) VALUES(11, 1);
INSERT INTO ratings (picture_id, rating) VALUES(11, 1);
INSERT INTO ratings (blurb_id, rating) VALUES(1, 0);
INSERT INTO ratings (blurb_id, rating) VALUES(1, 1);
INSERT INTO ratings (blurb_id, rating) VALUES(1, 1);
INSERT INTO ratings (blurb_id, rating) VALUES(3, 1);
INSERT INTO ratings (blurb_id, rating) VALUES(3, 0);
INSERT INTO ratings (blurb_id, rating) VALUES(3, 1);
INSERT INTO ratings (blurb_id, rating) VALUES(2, 1);
INSERT INTO ratings (blurb_id, rating) VALUES(2, 1);
INSERT INTO ratings (blurb_id, rating) VALUES(2, 0);
INSERT INTO ratings (blurb_id, rating) VALUES(2, 1);
INSERT INTO ratings (blurb_id, rating) VALUES(2, 1);
INSERT INTO ratings (blurb_id, rating) VALUES(3, 0);
INSERT INTO ratings (blurb_id, rating) VALUES(3, 0);
INSERT INTO ratings (blurb_id, rating) VALUES(3, 1);
INSERT INTO ratings (blurb_id, rating) VALUES(4, 1);
INSERT INTO ratings (blurb_id, rating) VALUES(4, 1);
INSERT INTO ratings (blurb_id, rating) VALUES(4, 0);
INSERT INTO ratings (blurb_id, rating) VALUES(4, 1);
INSERT INTO ratings (blurb_id, rating) VALUES(4, 0);
INSERT INTO ratings (blurb_id, rating) VALUES(4, 1);


INSERT INTO feedback (user_id, feedback_text) VALUES(1, 'Wow Amogh this profile and your whole app is amazing.');
INSERT INTO feedback (user_id, feedback_text) VALUES(2, 'I would add more hobbies rather than just your passion for burgers');